name: Deploy React App to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Step 3: Install dependencies and build the project
      - name: Install Dependencies and Build
        env: # Inject environment variables from GitHub Secrets
          VITE_APP_AWS_S3_BUCKET: ${{ secrets.VITE_API_BASE_URL }}
        run: |
          npm ci
          npm run build

      # Step 4: Rename the build output directory (if required)
      - name: Rename dist to counselling-frontend
        run: mv ./dist ./counselling-frontend

      # Step 5: Copy files to Lightsail
      - name: Copy Files to Lightsail
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.LIGHTSAIL_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_PRIVATE_KEY }}
          source: ./counselling-frontend/
          target: ~/deploy-temp/

      # Step 6: Deploy and configure on Lightsail
      - name: Deploy on Lightsail
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.LIGHTSAIL_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_PRIVATE_KEY }}
          script: |
            # Remove old deployment
            sudo rm -rf /var/www/html/counselling-frontend

            # Move new files to the deployment directory
            sudo mv ~/deploy-temp/* /var/www/html/

            # Remove temporary deployment folder
            sudo rm -rf ~/deploy-temp

            # Restart NGINX to apply changes
            sudo systemctl restart nginx
