name: Deploy Counselling App to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    name: Deploy Backend to AWS Lightsail
    runs-on: ubuntu-latest

    env:
      LIGHTSAIL_INSTANCE_IP: ${{ secrets.LIGHTSAIL_INSTANCE_IP }}
      SSH_KEY: ${{ secrets.LIGHTSAIL_PRIVATE_KEY }}
      USERNAME: ubuntu
      PROJECT_DIR: counselling-backend
      ENV_FILE_PATH: /home/ubuntu/counselling/.env/.env.development
      APP_NAME: counselling-backend
      PORT: 3300

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.LIGHTSAIL_INSTANCE_IP }}
          username: ${{ env.USERNAME }}
          key: ${{ env.SSH_KEY }}
          script: |
            # Remove existing Node.js and npm
            sudo apt-get remove -y nodejs npm || true

            # Install Node.js from NodeSource (version 18)
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs

            # Install PM2 globally if not installed
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi

            # Clone the repository or pull the latest changes
            if [ -d "${{ env.PROJECT_DIR }}" ]; then
              cd ${{ env.PROJECT_DIR }}
              git pull origin main
            else
              git clone https://github.com/${{ github.repository }} ${{ env.PROJECT_DIR }}
              cd ${{ env.PROJECT_DIR }}
            fi

            # Verify the contents of the project directory
            echo "Listing project directory contents:"
            ls -la

            # Install dependencies
            npm install

            # Ensure the environment file exists
            if [ ! -f "${{ env.ENV_FILE_PATH }}" ]; then
              echo ".env file is missing at ${{ env.ENV_FILE_PATH }}"
              exit 1
            else
              echo ".env file found. Copying to project root."
              cp ${{ env.ENV_FILE_PATH }} .env
            fi

            # Restart the application with PM2
            pm2 delete ${{ env.APP_NAME }} || true
            pm2 start npm --name ${{ env.APP_NAME }} -- run start
            pm2 save

  deploy-frontend:
    name: Deploy Frontend to AWS Lightsail
    runs-on: ubuntu-latest
    needs: deploy-backend

    env:
      LIGHTSAIL_INSTANCE_IP: ${{ secrets.LIGHTSAIL_INSTANCE_IP }}
      SSH_KEY: ${{ secrets.LIGHTSAIL_PRIVATE_KEY }}
      USERNAME: ubuntu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies and Build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
        run: |
          cd cbs-counseling-frontend
          npm ci
          npm run build

      - name: Rename dist to counselling-frontend
        run: mv cbs-counseling-frontend/dist ./counselling-frontend

      - name: Copy Files to Lightsail
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ env.LIGHTSAIL_INSTANCE_IP }}
          username: ${{ env.USERNAME }}
          key: ${{ env.SSH_KEY }}
          source: ./counselling-frontend/
          target: ~/deploy-temp/

      - name: Deploy on Lightsail
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ env.LIGHTSAIL_INSTANCE_IP }}
          username: ${{ env.USERNAME }}
          key: ${{ env.SSH_KEY }}
          script: |
            # Remove old deployment
            sudo rm -rf /var/www/html/counselling-frontend

            # Move new files to the deployment directory
            sudo mv ~/deploy-temp/* /var/www/html/

            # Remove temporary deployment folder
            sudo rm -rf ~/deploy-temp

            # Restart NGINX to apply changes
            sudo systemctl restart nginx
